[package]
name = "sol_tutorial_imgui"
version = "0.1.0"
authors = ["Markus RÃ¸yset <cosmicspacedragon@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.31.0", features = ["bundled"] }
lazy_static = "1.4.0"
